include SourceRoot.mk
include Objects.mk
include Common.mk

05-A64: $(addprefix $(OUTPUT_05A64)/, $(SOURCES:.cpp=.o))
	mkdir -p $(OUTPUT_ROOT)/Binaries/
	$(CC) ScratchLinux.cpp $^ $(CFLAGS_05A64) -o $(OUTPUT_ROOT)/Binaries/$@

07-PNR: $(addprefix $(OUTPUT_07PNR)/, $(SOURCES:.cpp=.o))
	mkdir -p $(OUTPUT_ROOT)/Binaries/
	$(CC) ScratchLinux.cpp $^ $(CFLAGS_07PNR) -o $(OUTPUT_ROOT)/Binaries/$@

08-NHM: $(addprefix $(OUTPUT_08NHM)/, $(SOURCES:.cpp=.o))
	mkdir -p $(OUTPUT_ROOT)/Binaries/
	$(CC) ScratchLinux.cpp $^ $(CFLAGS_08NHM) -o $(OUTPUT_ROOT)/Binaries/$@

11-BD1: $(addprefix $(OUTPUT_11BD1)/, $(SOURCES:.cpp=.o))
	mkdir -p $(OUTPUT_ROOT)/Binaries/
	$(CC) ScratchLinux.cpp $^ $(CFLAGS_11BD1) -o $(OUTPUT_ROOT)/Binaries/$@

11-SNB: $(addprefix $(OUTPUT_11SNB)/, $(SOURCES:.cpp=.o))
	mkdir -p $(OUTPUT_ROOT)/Binaries/
	$(CC) ScratchLinux.cpp $^ $(CFLAGS_11SNB) -o $(OUTPUT_ROOT)/Binaries/$@

13-HSW: $(addprefix $(OUTPUT_13HSW)/, $(SOURCES:.cpp=.o))
	mkdir -p $(OUTPUT_ROOT)/Binaries/
	$(CC) ScratchLinux.cpp $^ $(CFLAGS_13HSW) -o $(OUTPUT_ROOT)/Binaries/$@

14-BDW: $(addprefix $(OUTPUT_14BDW)/, $(SOURCES:.cpp=.o))
	mkdir -p $(OUTPUT_ROOT)/Binaries/
	$(CC) ScratchLinux.cpp $^ $(CFLAGS_14BDW) -o $(OUTPUT_ROOT)/Binaries/$@

16-KNL: $(addprefix $(OUTPUT_16KNL)/, $(SOURCES:.cpp=.o))
	mkdir -p $(OUTPUT_ROOT)/Binaries/
	$(CC) ScratchLinux.cpp $^ $(CFLAGS_16KNL) -o $(OUTPUT_ROOT)/Binaries/$@

17-ZN1: $(addprefix $(OUTPUT_17ZN1)/, $(SOURCES:.cpp=.o))
	mkdir -p $(OUTPUT_ROOT)/Binaries/
	$(CC) ScratchLinux.cpp $^ $(CFLAGS_17ZN1) -o $(OUTPUT_ROOT)/Binaries/$@

17-SKX: $(addprefix $(OUTPUT_17SKX)/, $(SOURCES:.cpp=.o))
	mkdir -p $(OUTPUT_ROOT)/Binaries/
	$(CC) ScratchLinux.cpp $^ $(CFLAGS_17SKX) -o $(OUTPUT_ROOT)/Binaries/$@

18-CNL: $(addprefix $(OUTPUT_18CNL)/, $(SOURCES:.cpp=.o))
	mkdir -p $(OUTPUT_ROOT)/Binaries/
	$(CC) ScratchLinux.cpp $^ $(CFLAGS_18CNL) -o $(OUTPUT_ROOT)/Binaries/$@

19-ZN2: $(addprefix $(OUTPUT_19ZN2)/, $(SOURCES:.cpp=.o))
	mkdir -p $(OUTPUT_ROOT)/Binaries/
	$(CC) ScratchLinux.cpp $^ $(CFLAGS_19ZN2) -o $(OUTPUT_ROOT)/Binaries/$@


