del "Launcher.sdf"
del "Launcher.VC.db"
rd /s /q ".vs\"
rd /s /q "ipch\"
rd /s /q "Debug\"
rd /s /q "Launcher\Debug\"
rd /s /q "Release\"
rd /s /q "Launcher\Release\"
rd /s /q "Developer\"
rd /s /q "Launcher\Developer\"
